[all]
releaser = tito.release.KojiGitReleaser
autobuild_tags = epel7 epel8 f33 f35
git_url = git+https://www.doubledog.org/git/mirrmaid.git

[test-all]
releaser = tito.release.KojiReleaser
autobuild_tags = epel7 epel8 f33 f35
builder.test = 1

[epel]
releaser = tito.release.KojiGitReleaser
autobuild_tags = epel7 epel8
git_url = git+https://www.doubledog.org/git/mirrmaid.git

[test-epel]
releaser = tito.release.KojiReleaser
autobuild_tags = epel7 epel8
builder.test = 1

[epel-7]
releaser = tito.release.KojiGitReleaser
autobuild_tags = epel7
git_url = git+https://www.doubledog.org/git/mirrmaid.git

[test-epel-7]
releaser = tito.release.KojiReleaser
autobuild_tags = epel7
builder.test = 1

[fedora]
releaser = tito.release.KojiGitReleaser
autobuild_tags = f33 f35
git_url = git+https://www.doubledog.org/git/mirrmaid.git

[test-fedora]
releaser = tito.release.KojiReleaser
autobuild_tags = f33 f35
builder.test = 1

[epel-8]
releaser = tito.release.KojiGitReleaser
autobuild_tags = epel8
git_url = git+https://www.doubledog.org/git/mirrmaid.git

[test-epel-8]
releaser = tito.release.KojiReleaser
autobuild_tags = epel8
builder.test = 1

[fedora-33]
releaser = tito.release.KojiGitReleaser
autobuild_tags = f33
git_url = git+https://www.doubledog.org/git/mirrmaid.git

[test-fedora-33]
releaser = tito.release.KojiReleaser
autobuild_tags = f33
builder.test = 1

[fedora-35]
releaser = tito.release.KojiGitReleaser
autobuild_tags = f35
git_url = git+https://www.doubledog.org/git/mirrmaid.git

[test-fedora-35]
releaser = tito.release.KojiReleaser
autobuild_tags = f35
builder.test = 1

