[centos-stream-9-x86_64]
releaser = tito.release.YumRepoReleaser
srpm_disttag = .el9
builder = tito.builder.MockBuilder
builder.mock = centos-stream+epel-9-x86_64
rsync = /mnt/florian-repos/c9s/x86_64/

[test-centos-stream-9-x86_64]
releaser = tito.release.YumRepoReleaser
srpm_disttag = .el9
builder = tito.builder.MockBuilder
builder.mock = centos-stream+epel-9-x86_64
builder.test = 1
rsync = /mnt/florian-repos/test/c9s/x86_64/
